version: '3.1'

services:

    mysql:
        image: mysql:5.7
        container_name: keycloak-mysql
        env_file: ./env/.env-mysql
        volumes:
            #- ./mysqldump:/docker-entrypoint-initdb.d # Directory to load sql files from. Remember to create this dir first.
            - mysql-keycloak-accounts:/var/lib/mysql
    keycloak:
        image: jboss/keycloak:3.2.1.Final #this is the latest
        container_name: keycloak
        links:
            - mysql:mysql # No need for this??

        # Username & password to use the database
        env_file: ./env/.env-keycloak

        environment:
            # Select database
            - DB_VENDOR=MYSQL
            # proxy address forwarding, needed when running Keycloak behind a proxy
            - PROXY_ADDRESS_FORWARDING=true
            - TZ=Europe/Stockholm
            # URL for proxy server
        ports:
            - 8080:8080
        volumes:
            - ./keycloak/configuration/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
            - ./keycloak/themes/dina:/opt/jboss/keycloak/themes/dina
        depends_on:
            - mysql



volumes:
    mysql-keycloak-accounts:
